// ============================================================
// PulseAnalytics Demo Event Seeder
// ============================================================
//
// Creates realistic analytics data for local development.
//
// IMPORTANT:
// This script only removes events created by this demo
// seeder. It does NOT remove manually created events.
//
// ============================================================

import "dotenv/config";

import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client.js";

// ============================================================
// Prisma Setup
// ============================================================

const databaseUrl = process.env.DATABASE_URL;

if (!databaseUrl) {
  throw new Error(
    "DATABASE_URL is not defined."
  );
}

const adapter = new PrismaPg({
  connectionString: databaseUrl,
});

const prisma = new PrismaClient({
  adapter,
});

// ============================================================
// Demo Workspace
// ============================================================

const WORKSPACE_ID =
  "cmugn5md70000hw9wz6nb7ubj";

// ============================================================
// Demo User
// ============================================================

const USER_ID =
  "cmugn5mrx0001hw9wjf5ll8r6";

// ============================================================
// Demo Event Definitions
// ============================================================

const eventDefinitions = [
  {
    name: "page_viewed",
    pageUrl: "/",
    pageTitle: "Home",
  },
  {
    name: "page_viewed",
    pageUrl: "/pricing",
    pageTitle: "Pricing",
  },
  {
    name: "page_viewed",
    pageUrl: "/features",
    pageTitle: "Features",
  },
  {
    name: "page_viewed",
    pageUrl: "/dashboard",
    pageTitle: "Dashboard",
  },
  {
    name: "button_clicked",
    pageUrl: "/pricing",
    pageTitle: "Pricing",
  },
  {
    name: "button_clicked",
    pageUrl: "/",
    pageTitle: "Home",
  },
  {
    name: "signup_started",
    pageUrl: "/signup",
    pageTitle: "Create Account",
  },
  {
    name: "signup_completed",
    pageUrl: "/signup",
    pageTitle: "Create Account",
  },
  {
    name: "feature_used",
    pageUrl: "/dashboard",
    pageTitle: "Dashboard",
  },
  {
    name: "checkout_started",
    pageUrl: "/checkout",
    pageTitle: "Checkout",
  },
];

// ============================================================
// Device Definitions
// ============================================================

const devices = [
  {
    deviceType: "desktop",
    browser: "Chrome",
    operatingSystem: "Windows",
  },
  {
    deviceType: "desktop",
    browser: "Safari",
    operatingSystem: "macOS",
  },
  {
    deviceType: "mobile",
    browser: "Chrome",
    operatingSystem: "Android",
  },
  {
    deviceType: "mobile",
    browser: "Safari",
    operatingSystem: "iOS",
  },
  {
    deviceType: "tablet",
    browser: "Safari",
    operatingSystem: "iPadOS",
  },
];

// ============================================================
// Location Definitions
// ============================================================

const locations = [
  {
    country: "India",
    city: "Kolkata",
  },
  {
    country: "India",
    city: "Mumbai",
  },
  {
    country: "India",
    city: "Bengaluru",
  },
  {
    country: "United States",
    city: "New York",
  },
  {
    country: "United Kingdom",
    city: "London",
  },
];

// ============================================================
// Create Demo Data
// ============================================================

async function main() {
  console.log(
    "\nCreating PulseAnalytics demo events...\n"
  );

  // ----------------------------------------------------------
  // Find the demo user
  // ----------------------------------------------------------

  const user =
    await prisma.user.findFirst({
      where: {
        id: USER_ID,
        workspaceId: WORKSPACE_ID,
      },
    });

  if (!user) {
    throw new Error(
      "Demo user not found. Run npm run seed first."
    );
  }

  // ----------------------------------------------------------
  // Remove only events generated by this demo script.
  //
  // We identify them using a special property:
  // { "demoSeed": true }
  //
  // ----------------------------------------------------------

  const deleted =
    await prisma.event.deleteMany({
      where: {
        workspaceId: WORKSPACE_ID,

        properties: {
          path: ["demoSeed"],
          equals: true,
        },
      },
    });

  console.log(
    `Removed ${deleted.count} previous demo events.`
  );

  // ----------------------------------------------------------
  // Create demo sessions
  // ----------------------------------------------------------

  const sessions = [];

  for (
    let i = 0;
    i < devices.length;
    i++
  ) {
    const device = devices[i];

    const location =
      locations[i % locations.length];

    const startedAt = new Date();

    startedAt.setDate(
      startedAt.getDate() - i
    );

    startedAt.setHours(
      9 + i,
      15,
      0,
      0
    );

    const session =
      await prisma.session.create({
        data: {
          workspaceId: WORKSPACE_ID,
          userId: user.id,

          startedAt,

          deviceType:
            device.deviceType,

          browser:
            device.browser,

          operatingSystem:
            device.operatingSystem,

          country:
            location.country,

          city:
            location.city,
        },
      });

    sessions.push(session);
  }

  console.log(
    `Created ${sessions.length} demo sessions.`
  );

  // ----------------------------------------------------------
  // Create demo events
  // ----------------------------------------------------------

  let createdEvents = 0;

  for (
    let i = 0;
    i < 60;
    i++
  ) {
    const definition =
      eventDefinitions[
        i % eventDefinitions.length
      ];

    const session =
      sessions[
        i % sessions.length
      ];

    // Spread events across the last 10 days.

    const timestamp = new Date();

    const daysAgo = i % 10;

    timestamp.setDate(
      timestamp.getDate() - daysAgo
    );

    // Spread events throughout the day.

    timestamp.setHours(
      8 + (i % 10),
      (i * 7) % 60,
      (i * 13) % 60,
      0
    );

    await prisma.event.create({
      data: {
        workspaceId:
          WORKSPACE_ID,

        userId: user.id,

        sessionId:
          session.id,

        name: definition.name,

        properties: {
          demoSeed: true,

          source:
            "pulseanalytics-demo",

          sequence:
            i + 1,
        },

        pageUrl:
          `https://demo.pulseanalytics.local${definition.pageUrl}`,

        pageTitle:
          definition.pageTitle,

        timestamp,

        createdAt: timestamp,
      },
    });

    createdEvents++;
  }

  // ----------------------------------------------------------
  // Summary
  // ----------------------------------------------------------

  console.log(
    `Created ${createdEvents} demo events.`
  );

  console.log(
    `Created ${sessions.length} demo sessions.`
  );

  console.log(
    "\nDemo data is ready."
  );

  console.log(
    "Open http://localhost:3000/events to test filters."
  );

  console.log(
    "====================================================\n"
  );
}

// ============================================================
// Execute
// ============================================================

main()
  .catch((error) => {
    console.error(
      "\nDemo seed failed:",
      error
    );

    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });