"use client";

// ============================================================
// AIInsight
// ============================================================
//
// Displays a data-driven analytics insight generated by the
// PulseAnalytics backend.
//
// The backend currently uses rule-based analytics.
// An actual AI/LLM layer can be added later.
//
// The workspace is taken from the authenticated user so that
// each user only receives insights for their own workspace.
//
// ============================================================

import { useEffect, useState } from "react";

import {
  Sparkles,
  TrendingUp,
  TrendingDown,
  Minus,
} from "lucide-react";

import { useAuth } from "@/context/AuthContext";

import {
  getAnalyticsInsight,
  type AnalyticsInsight as AnalyticsInsightData,
} from "@/lib/api";

// ============================================================
// Component Props
// ============================================================

interface AIInsightProps {
  days: number;
}

// ============================================================
// AIInsight Component
// ============================================================

export function AIInsight({
  days,
}: AIInsightProps) {
  // ==========================================================
  // Authentication / Workspace
  // ==========================================================

  const {
    workspace,
    loading: authLoading,
  } = useAuth();

  // ==========================================================
  // Component State
  // ==========================================================

  const [insight, setInsight] =
    useState<AnalyticsInsightData | null>(
      null
    );

  const [loading, setLoading] =
    useState(true);

  const [error, setError] =
    useState<string | null>(null);

  // ==========================================================
  // Load Insight
  // ==========================================================

  useEffect(() => {
    // Wait until authentication has finished and a workspace
    // is available.
    if (authLoading || !workspace) {
      return;
    }

    // Use the authenticated workspace instead of the
    // hardcoded workspace ID.
    const workspaceId = workspace.id;

    async function loadInsight() {
      try {
        setError(null);

        const response =
          await getAnalyticsInsight(
            workspaceId,
            days
          );

        setInsight(response.data);
      } catch (error) {
        console.error(
          "Failed to load analytics insight:",
          error
        );

        setError(
          "Unable to generate analytics insight."
        );
      } finally {
        setLoading(false);
      }
    }

    loadInsight();
  }, [
    workspace,
    authLoading,
    days,
  ]);

  // ==========================================================
  // Determine Trend Icon
  // ==========================================================

  const TrendIcon =
    insight === null
      ? Minus
      : insight.activityChange > 0
        ? TrendingUp
        : insight.activityChange < 0
          ? TrendingDown
          : Minus;

  // ==========================================================
  // Render
  // ==========================================================

  return (
    <section className="mt-6 overflow-hidden rounded-2xl border border-emerald-200 bg-emerald-50/60 p-6 dark:border-emerald-900 dark:bg-emerald-950/20">

      {/* ======================================================
          Insight Container
          ====================================================== */}

      <div className="flex flex-col gap-5 md:flex-row md:items-start">

        {/* ====================================================
            AI Icon
            ==================================================== */}

        <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-emerald-600 text-white shadow-sm">
          <Sparkles size={20} />
        </div>

        {/* ====================================================
            Insight Content
            ==================================================== */}

        <div className="flex-1">

          {/* Small section label */}

          <div className="flex items-center gap-2">
            <p className="text-xs font-semibold uppercase tracking-wider text-emerald-700 dark:text-emerald-400">
              Analytics insight
            </p>

            {!loading &&
              insight && (
                <TrendIcon
                  size={15}
                  className="text-emerald-600 dark:text-emerald-400"
                />
              )}
          </div>

          {/* ==================================================
              Loading State
              ================================================== */}

          {loading && (
            <>
              <div className="mt-3 h-5 w-72 animate-pulse rounded bg-emerald-100 dark:bg-emerald-900/40" />

              <div className="mt-3 space-y-2">
                <div className="h-3 w-full max-w-2xl animate-pulse rounded bg-emerald-100 dark:bg-emerald-900/40" />

                <div className="h-3 w-4/5 max-w-xl animate-pulse rounded bg-emerald-100 dark:bg-emerald-900/40" />
              </div>
            </>
          )}

          {/* ==================================================
              Error State
              ================================================== */}

          {!loading && error && (
            <div className="mt-3">
              <h3 className="text-base font-semibold text-slate-950 dark:text-white">
                Insight unavailable
              </h3>

              <p className="mt-2 text-sm text-slate-600 dark:text-slate-300">
                {error}
              </p>
            </div>
          )}

          {/* ==================================================
              Insight
              ================================================== */}

          {!loading &&
            !error &&
            insight && (
              <>
                <h3 className="mt-1.5 text-base font-semibold text-slate-950 dark:text-white">
                  {insight.title}
                </h3>

                <p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600 dark:text-slate-300">
                  {insight.description}
                </p>

                {/* Insight metadata */}

                <div className="mt-4 flex flex-wrap items-center gap-3 text-xs text-slate-500 dark:text-slate-400">

                  <span className="rounded-lg bg-white/70 px-2.5 py-1.5 dark:bg-slate-900/50">
                    {days} day period
                  </span>

                  {insight.topEvent !==
                    "No events yet" && (
                    <span className="rounded-lg bg-white/70 px-2.5 py-1.5 dark:bg-slate-900/50">
                      Top event:{" "}
                      <span className="font-medium text-slate-700 dark:text-slate-300">
                        {insight.topEvent}
                      </span>
                    </span>
                  )}

                  {insight.activityChange !==
                    0 && (
                    <span className="rounded-lg bg-white/70 px-2.5 py-1.5 dark:bg-slate-900/50">
                      {insight.activityChange > 0
                        ? "+"
                        : ""}
                      {insight.activityChange}%
                      vs previous period
                    </span>
                  )}

                </div>
              </>
            )}

        </div>
      </div>
    </section>
  );
}