// ============================================================
// Events Page
// ============================================================
//
// Event explorer for PulseAnalytics.
//
// Later this page will:
// - Fetch events from PostgreSQL
// - Filter by event name
// - Filter by user
// - Filter by date
// - Show event properties
// - Support pagination
//
// ============================================================

import {
  Activity,
  Filter,
  MousePointerClick,
  Search,
} from "lucide-react";

const events = [
  {
    name: "button_clicked",
    user: "user_1024",
    properties: "pricing_cta",
    time: "Just now",
  },
  {
    name: "page_viewed",
    user: "user_2841",
    properties: "/dashboard",
    time: "12 sec ago",
  },
  {
    name: "signup_completed",
    user: "user_3921",
    properties: "google",
    time: "28 sec ago",
  },
  {
    name: "checkout_started",
    user: "user_8124",
    properties: "pro_plan",
    time: "41 sec ago",
  },
  {
    name: "feature_used",
    user: "user_1928",
    properties: "export_report",
    time: "1 min ago",
  },
];

export default function EventsPage() {
  return (
    <div className="min-h-screen bg-slate-50 text-slate-950 dark:bg-slate-900 dark:text-white">

      {/* Header */}

      <header className="border-b border-slate-200 bg-white px-4 py-5 dark:border-slate-800 dark:bg-slate-950 md:px-8">
        <div className="mx-auto max-w-[1600px]">

          <p className="text-sm font-medium text-emerald-600 dark:text-emerald-400">
            Product activity
          </p>

          <h1 className="mt-1 text-2xl font-semibold tracking-tight md:text-3xl">
            Events
          </h1>

          <p className="mt-1.5 text-sm text-slate-500 dark:text-slate-400">
            Explore the events being generated by your product.
          </p>

        </div>
      </header>

      <main className="mx-auto max-w-[1600px] p-4 md:p-8">

        {/* Search and filters */}

        <div className="flex flex-col gap-3 md:flex-row">

          <div className="relative flex-1">

            <Search
              size={17}
              className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"
            />

            <input
              type="text"
              placeholder="Search events..."
              className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-10 pr-4 text-sm outline-none placeholder:text-slate-400 focus:border-emerald-500 dark:border-slate-800 dark:bg-slate-950"
            />

          </div>

          <button className="flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-medium dark:border-slate-800 dark:bg-slate-950">
            <Filter size={16} />
            Filters
          </button>

        </div>

        {/* Event table */}

        <div className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-950">

          <div className="overflow-x-auto">

            <table className="w-full min-w-[700px] text-left text-sm">

              <thead className="border-b border-slate-200 bg-slate-50 dark:border-slate-800 dark:bg-slate-900">

                <tr>
                  <th className="px-5 py-4 font-medium text-slate-500">
                    Event
                  </th>

                  <th className="px-5 py-4 font-medium text-slate-500">
                    User
                  </th>

                  <th className="px-5 py-4 font-medium text-slate-500">
                    Properties
                  </th>

                  <th className="px-5 py-4 font-medium text-slate-500">
                    Time
                  </th>
                </tr>

              </thead>

              <tbody>

                {events.map((event) => (
                  <tr
                    key={`${event.name}-${event.user}`}
                    className="border-b border-slate-100 last:border-0 dark:border-slate-800"
                  >

                    <td className="px-5 py-4">

                      <div className="flex items-center gap-3">

                        <div className="rounded-lg bg-emerald-50 p-2 text-emerald-600 dark:bg-emerald-950/50 dark:text-emerald-400">
                          <MousePointerClick size={16} />
                        </div>

                        <span className="font-medium">
                          {event.name}
                        </span>

                      </div>

                    </td>

                    <td className="px-5 py-4 text-slate-600 dark:text-slate-400">
                      {event.user}
                    </td>

                    <td className="px-5 py-4 text-slate-600 dark:text-slate-400">
                      {event.properties}
                    </td>

                    <td className="px-5 py-4 text-slate-500">
                      {event.time}
                    </td>

                  </tr>
                ))}

              </tbody>

            </table>

          </div>

          {/* Footer */}

          <div className="flex items-center justify-between border-t border-slate-200 px-5 py-4 text-xs text-slate-500 dark:border-slate-800">
            <span>Showing recent events</span>

            <div className="flex items-center gap-2">
              <Activity size={14} />
              Live event ingestion will be connected later.
            </div>
          </div>

        </div>

      </main>
    </div>
  );
}